<?php
namespace App\Http\DashboardModelControllers;


use App\Models\Coverage;
use App\Models\Outlet;

class CoverageDashboardModelController extends DashboardModelController {
    public function getFields() {
        return [
            'name' => array(
                'type' => 'string'
            ),
            'description' => array(
                'type' => 'text'
            ),
            'outlet_id' => array(
                'label' => 'Outlet',
                'type' => 'relation',
                'relationType' => 'belongsTo',
                'model' => 'Outlet',
                'path' => '/outlet',
                'foreign_key' => 'id'
            )
        ];
    }
    public function getBelongsToFields($model) {
        if ($model == 'Outlet') {
            return Outlet::all();
        }
    }
    public function deleteObject($id) {
        return Coverage::delete($id);
    }
    public function updateObject($id, $validator) {
        return Coverage::where('id', $id)->update($validator);
    }
    public function saveObject($validator) {
        return Coverage::create($validator);
    }
    public function getObject($id) {
        return Coverage::first('id', $id);
    }
    public function getObjects() {
        return Coverage::find();
    }
    public function getSingularRoute()
    {
        return 'coverage'; // TODO: Change the autogenerated stub
    }
    public function getLowerCasePlural()
    {
        return 'objects'; // TODO: Change the autogenerated stub
    }
    public function getLowerCaseSingular()
    {
        return 'coverage'; // TODO: Change the autogenerated stub
    }
    public function getModel()
    {
        return "Coverage"; // TODO: Change the autogenerated stub
    }
    public function getVueModel()
    {
        return parent::getVueModel(); // TODO: Change the autogenerated stub
    }
    public function getClassModel() {
        return "Coverage";
    }
    public function getPluralRoute() {
        return "coverages";
    }
}
