<?php
namespace App\Http\DashboardModelControllers;


use App\Models\Outlet;

class OutletDashboardModelController extends DashboardModelController {
    public function getFields() {
        return [
            'name' => array(
                'type' => 'string'
            ),
            'description' => array(
                'type' => 'description'
            )
        ];
    }
    public function deleteObject($id) {
        return Outlet::delete($id);
    }
    public function updateObject($id, $validator) {
        return Outlet::where('id', $id)->update($validator);
    }
    public function saveObject($validator) {
        return Outlet::create($validator);
    }
    public function getObject($id) {
        return Outlet::first('id', $id);
    }
    public function getObjects() {
        return Outlet::find();
    }
    public function getSingularRoute()
    {
        return 'outlet'; // TODO: Change the autogenerated stub
    }
    public function getLowerCasePlural()
    {
        return 'objects'; // TODO: Change the autogenerated stub
    }
    public function getLowerCaseSingular()
    {
        return 'outlet'; // TODO: Change the autogenerated stub
    }
    public function getModel()
    {
        return "Outlet"; // TODO: Change the autogenerated stub
    }
    public function getVueModel()
    {
        return parent::getVueModel(); // TODO: Change the autogenerated stub
    }
    public function getClassModel() {
        return "Outlet";
    }
    public function getPluralRoute() {
        return "outlets";
    }
}
