<?php
namespace App\Http\DashboardModelControllers;


class CoverageDashboardModelController extends DashboardModelController {
    public function getFields() {
        return [
            'name' => array(
                'type' => 'string'
            ),
            'description' => array(
                'type' => 'description'
            )
        ];
    }
    public function getSingleRoute()
    {
        return 'coverage'; // TODO: Change the autogenerated stub
    }
    public function getListRoute()
    {
        return 'coverages'; // TODO: Change the autogenerated stub
    }
    public function getModel()
    {
        return "Coverage"; // TODO: Change the autogenerated stub
    }
    public function getVueModel()
    {
        return parent::getVueModel(); // TODO: Change the autogenerated stub
    }
}
